export const IMAGES = {
	LOAD: 'IMAGES_LOAD',
	LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
	LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

export const STATS = {
	LOAD: 'IMAGE_LOAD_STATS',
	LOAD_SUCCESS: 'IMAGE_LOAD_STATS_SUCCESS',
	LOAD_FAIL: 'IMAGE_LOAD_STATS_FAIL',
};
