export const AUTH_TOKEN_VALIDATED = 'AUTH_TOKEN_VALIDATED';
export const AUTH_USER_FETCHED = 'AUTH_USER_FETCHED';
export const AUTH_USER_FETCHED_ERROR = 'AUTH_USER_FETCHED_ERROR';
export const USER_KEY_LOCAL_STORAGE = 'FINANCIAL_CONTROL_TOKEN';
