export const BILLING_CYCLE_LOADING = 'BILLING_CYCLE_LOADING';

export const BILLING_CYCLE_SAVE_LOADING = 'BILLING_CYCLE_SAVE_LOADING';

export const BILLING_CYCLE_ERROR = 'BILLING_CYCLE_ERROR';

export const BILLING_CYCLE_SAVE_ERROR = 'BILLING_CYCLE_SAVE_ERROR';

export const BILLING_CYCLE_SUCCESS = 'BILLING_CYCLE_SUCCESS';

export const BILLING_CYCLE_SAVE_SUCCESS = 'BILLING_CYCLE_SAVE_SUCCESS';
